-- Run this SQL in your Supabase SQL Editor to create the necessary tables for this app

CREATE TABLE public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  client_name TEXT,
  completion_date TEXT,
  technologies_used TEXT,
  featured_image TEXT NOT NULL,
  gallery_images TEXT[],
  tags TEXT[],
  project_url TEXT,
  status TEXT DEFAULT 'published',
  featured BOOLEAN DEFAULT false,
  seo_title TEXT,
  seo_description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  icon TEXT NOT NULL,
  description TEXT NOT NULL,
  order_num INTEGER
);

CREATE TABLE public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  icon TEXT NOT NULL,
  progress INTEGER NOT NULL,
  order_num INTEGER
);

CREATE TABLE public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  company TEXT NOT NULL,
  rating INTEGER NOT NULL,
  review TEXT NOT NULL,
  client_photo TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'unread',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL
);

-- Note: Ensure Row Level Security (RLS) is disabled or properly configured for these tables
-- if you plan on fetching this data directly on the client side.
